### ISSUE TITLE
results-partB

### ISSUE THREAD

**Issue by Ginfung** [Ginfung/Reports#17]
Basing on the SATIBEA algorithm
![eshop](https://cloud.githubusercontent.com/assets/3222148/16182855/a46ea434-3678-11e6-9e58-878d7bcb9b65.png)
![fiasco](https://cloud.githubusercontent.com/assets/3222148/16182857/a6d31d22-3678-11e6-931d-93eb2aec2708.png)
![ecos](https://cloud.githubusercontent.com/assets/3222148/16182858/a96417a8-3678-11e6-92a0-3c1e8e1220f6.png)
![freebsd](https://cloud.githubusercontent.com/assets/3222148/16182860/abfc9152-3678-11e6-9997-91dfd9200790.png)
![linux](https://cloud.githubusercontent.com/assets/3222148/16182862/ae55fcb8-3678-11e6-9df9-2aaeef42f886.png)
![uclinux](https://cloud.githubusercontent.com/assets/3222148/16182863/b0a8eaa2-3678-11e6-922c-8daa555168fe.png)

**Comment by Ginfung** [comment]
@timm 1) actually, the difference of IGDs between gen0 and final_gen is one-order (10x), except the linux (about 100x)

2) I found something incorrect in  SWAY4B and SWAY4C  (it seems the output returns only one cluster of the WHERE, that is, all output candidates are very similar, making the igd very large ~= gen0)
I need to check this. This result is not consistent with the experiment I did last week. I need to debug the code I modified this week

**Comment by Ginfung** [comment]
@timm  since the sway4b or sway4c might be problematic, I won't report the hypervolume and spread at this time. I need to debug them first

**Comment by timm** [comment]
to be clear: all the good result seen so far have been with sway4b?

and the new sway4c results are problematic cause of small number of returned instances?

fyi- sway4c will only return 1 leaf cluster UNLESS some epsilon is added to the domination test

i.e. not a < b 
but a*1.05 < b

here epsilon = 1.05

now don't go crazy here. the issue is not sway4c vs sway4b but {allTheOtherMethods} vs sway

if sway4b is consistently best then use that (but rerun the ssbse models to ensure that boolean beats continous)

**Comment by Ginfung** [comment]
I need to check why the result sucks after I midified the seay yesterday.
Since all statistic methods are compketely the same, there must be
problmatic at sway.py.
Again, thank you very much. I know what to focus at this time.

**Comment by Ginfung** [comment]
fixed. see #18
